name: ayame9joe
description: playful thoughts
meta_description: "ayame9joe, playful thoughts"

aboutPage: true

markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify",”no_intra_emphasis”, “underline”, “quote”, “footnotes"]
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://ayame9joe.github.com'
google_analytics: 'UA-45533098-2'
disqus: true
disqus_shortname: ‘ayame9joe’

# Details for the RSS feed generator
url:            ‘ayame9joe.github.io’
author:         'ayame9joe'
authorTwitter:  'ayame9joe'

permalink:       /:year/:title/



defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
